status = [
    "continuous-integration/travis-ci/push"
]
block_labels = ["Wait to merge âœ‹"]
pr_status = [
    "code-review/reviewable"
]
delete_merged_branches = true
cut_body_after = "<!-- Reviewable:start -->"
